[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_APP_BACKEND = "https://ellyan-workout-tracker-688cc4f8fd74.herokuapp.com"
  VITE_APP_ENV = "production"
  VITE_PUBLIC_PATH = "/photos"
